### ISSUE TITLE
Rank and Unlocks randomly getting reseted.

### ISSUE THREAD

**Issue by MrPyroPT** [Savage-Game-Design/Mike-Force#69] opened 2021-05-14 10:40 UTC
**Describe the bug**
well, if experienced this a couple of times. yesterday i got 3 resets randomly. 

 ***the mission didnt restart, it just randomly resets***

**To Reproduce**
sometimes happens when servers restart.

**Comment by Dave4291** [comment] 2021-05-16 10:46
Duplicate of #11

**Comment by Alablm** [comment] 2021-12-24 00:10
Closing - Duplicate #11

**Closed as completed by Alablm** 2021-12-24 00:10 UTC
Labels: bug, confirmed
