### ISSUE TITLE
Critical Bug: Cannot turn a red zone to green (Destroy Enemy Supplies and Destroy Sites Objective) - v0.66.01

### ISSUE THREAD

**Issue by DooblyNoobly** [Savage-Game-Design/Mike-Force#131] opened 2021-10-27 07:16 UTC
**Describe the bug**

The objectives [Destroy Enemy Supplies] and [Destroy Sites] objectives can't be completed which makes turning red zone to green impossible.

**To Reproduce**

- Clear all sites (AA, Artillery) around red zone South-East of FOB5
- Destroy HQ and all supplies around HQ
- Notice that the objectives for [Destroy Enemy Supplies] and [Destroy Sites] do not change to completed
- Repel all counter attacks, kill all enemy units in red zone and wait
- Notice that zone does not turn to green and objectives still haven't changed to complete

**Screenshots**

All sites destroyed:
![image](https://user-images.githubusercontent.com/20813925/139017512-8a36091a-cfda-4c5f-a7bb-2075aa5ea9f8.png)

We destroyed the 3 supply crates and radio at HQ using breaching charges, the HQ marker disappeared but notice the objective does not change:
![image](https://user-images.githubusercontent.com/20813925/139017731-d234e8f4-b9eb-45c3-ad7f-15a7d765e2da.png)

**Environment (please complete the following information):**
Version: 0.66.01
Map (specify if Altis Blufor): Cam Lao

* [ ] Official Server
* [ ] Official InDev Server
* [X] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods: none
    
Time the bug occurred (Please leave in GMT+10): Happens all the time, we haven't been able to progress in the game at all. Our server has been up for 3 weeks.

**Comment by Alablm** [comment] 2021-11-09 07:57
There is an artillery post on the north side of Ba Ria in your first screenshot. That is likely within the 1.2km zone distance and is why the zone isin't completing. Also, you need to kill a certain number of enemy units for the zone to complete

**Comment by Alablm** [comment] 2021-12-07 23:28
Closing as I believe this to be working as intended

**Closed as completed by Alablm** 2021-12-07 23:28 UTC
Labels: bug
