### ISSUE TITLE
Slingloading of Guntruck with Seahorse = bang

### ISSUE THREAD

**Issue by ashton1cav** [Savage-Game-Design/Mike-Force#17] opened 2021-05-09 03:50 UTC
**Describe the bug**
When attempting to slingload a gun truck with a seahorse the chopper will lock up and explode.

**To Reproduce**
Slingload a gun truck with a seahorse

**Expected behaviour**
Not sure, but my guess is the seahorse is not meant to be able to slingload the guntruck.

**Screenshots**
https://drive.google.com/file/d/1xpcvL4gInC0lQDEBoGB7dG1teTGLwopd/view - around 42 seconds

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): Cao Lao Nam - Mike Force

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [X] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:TFAR Beta, CBA A3
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: N/A

**Additional context**
Server is running latest Mike Force.

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Spoffy** [comment] 2021-05-09 14:22
Hah, nice catch - I'll investigate!

**Comment by Alablm** [comment] 2021-05-10 12:59
@Spoffy  This is caused by the vehicle locking script - when they physics turns off it tends to create a bad time for the helicopter. 

@ashton1cav workaround for now is to have someone ride in the vehicle you wish to sling, this will prevent the physics from being turned off.

**Comment by Alablm** [comment] 2021-12-08 00:42
Closing as this has been fixed

**Closed as completed by Alablm** 2021-12-08 00:42 UTC
Labels: bug, confirmed
