### ISSUE TITLE
Wreck Recovery Bug

### ISSUE THREAD

**Issue by backseat1-1** [Savage-Game-Design/Mike-Force#118] opened 2021-07-13 16:15 UTC
**Describe the bug**
Unable to sling-load packed wrecks/pick up wreck. Becomes static object. 

**To Reproduce**
Packed wreck was sunk to the bottom of river. No option to pick up was presented when diving down to wreck. Admin placed wreck on shore. Was still unable to pick up/sling load/interact with object.

**Expected behaviour**
Dive down to packed wreck, pick up, swim to shore, RTB with wreck.

Version: v0.65.03
Port West of Ban Hoang

Official Server 1

No mods

**Comment by Alablm** [comment] 2021-12-04 13:47
We were unable to reproduce this internally, however we have implemented a potential fix for this in the latest internal version of Mike Force.

**Comment by Alablm** [comment] 2021-12-23 23:49
Hopefully fixed in release 0.66.02

**Closed as completed by Alablm** 2021-12-23 23:49 UTC
Labels: bug, confirmed
