### ISSUE TITLE
Packed Wreck container physics bug out

### ISSUE THREAD

**Issue by CurePindal** [Savage-Game-Design/Mike-Force#139] opened 2022-03-07 11:22 UTC
**Describe the bug**
Packed Wreck container physics bug out.
Everytime a wreck is packed on the off. Mike Force servers the resulting container flips wildly and often hits and kills anybody in the range of a few meters.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
- pack almost any wreck on any terrain
- container tends to flip wildly

**Expected behaviour**
Wreck container is placed properly without flipping like a dolphin on land.

**Environment (please complete the following information):**
Version: 

* [x ] Official Server
* [ ] Official InDev Server

Additional mods:
none    

Time the bug occurred (Please leave in GMT+0):
regularitly, easily reproducable

**Comment by Alablm** [comment] 2022-03-09 01:25
I personally cant reproduce, but I have a change in for an unrelated feature that should address this, closing for now

**Closed as completed by Alablm** 2022-03-09 01:25 UTC
Labels: bug
