### ISSUE TITLE
Master Arm Menu bug

### ISSUE THREAD

**Issue by backseat1-1** [Savage-Game-Design/Mike-Force#117] opened 2021-07-13 16:05 UTC
**Describe the bug**
Pilots are sometimes unable to access Master Arms menu at Pleiku.

**To Reproduce**
Trigger unknown. May be something to do with withstanding in chopper or having co-pilot present. Respawning seems to fix this problem

**Expected behaviour**
Master Arm access at Pleiku

Pleiku Airbase
Version: v0.65.03

Official Server 1

No mods
    
Multiple occurrences for myself, and other pilots

**Comment by Alablm** [comment] 2022-03-19 09:36
Not enough info/cant reproduce/cdlc, closing

**Closed as completed by Alablm** 2022-03-19 09:36 UTC
Labels: bug, CDLC
