### ISSUE TITLE
Logistics Inventory for Trucks Broken

### ISSUE THREAD

**Issue by jrwsdev** [Savage-Game-Design/Mike-Force#140] opened 2022-03-22 14:17 UTC
**Describe the bug**
When Light Ammo Supplies are added to a truck they do not show in the inventory and can't be unloaded. While you can unload anything already on the truck it's inventory is screwed up going forward until the truck respawns.

**To Reproduce**
Host a server and run Cam Lao Nam.
Go A Cav and Select Engineer training.
Unlock a M54 Truck.
Drive it over where supplies spawn.
Go to the Supply Officer and select Building Supplies, Medical Supplies and Light Ammo Supplies.
***
NOTE: Not sure if this is linked to the bug but instead of listed as a separate issue I am adding it here in case this is why I get the main bug. When I click to add the Light Ammo Supplies I get this message: No Entry 'bin\config.bin/CfgMagazines.ACRE_PRC343'.
***
Go back to the truck and view Logistics Inventory. It should say M54 Transport and list Weight 0/600.
Load the Building Supplies.
View the Logistics Inventory and see the item and the Weight is updated.
Load the Medical Supplies.
View the Logistics Inventory and see the item and the Weight is updated. Note there is still space for Ammo.
Load the Light Ammo Supplies.
View the Logistics Inventory and the information at the top is gone. No vehicle type or weight is shown. The light ammo is gone.

**Expected behaviour**
Light Ammo should work like the other supplies. I have loaded several combinations of the other items and this one is the only one that does it.

**Environment (please complete the following information):**
Version: 0.66.05
Map (Cam Lao Nam Blufor):

**Comment by jrwsdev** [comment] 2022-03-22 17:25
Ignore the task. I missed deleting it in the template and when I try to edit the text it doesn't let me.

**Comment by Alablm** [comment] 2022-04-11 16:00
Unable to reproduce on current build. Likely caused by mission modifications. Closing.

**Closed as completed by Alablm** 2022-04-11 16:00 UTC
Labels: bug
